# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
    deb-systemd-invoke stop s9100-monitor.service >/dev/null
    deb-systemd-invoke stop fancontrol.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/s9100-monitor" ]; then
    invoke-rc.d s9100-monitor stop || exit $?
fi
if [ -x "/etc/init.d/fancontrol" ]; then
    invoke-rc.d fancontrol stop || exit $?
fi
# End automatically added section

